### PR TITLE
(feat): add total steps number prop

### PR DESCRIPTION
**Pull request by Duduzera1997**
Add `totalStepsNumber` property to customization the CopilotStep;

### CODE REVIEW

**Comment by bryanltobing** [comment]
looking for this as well

**Review by bryanltobing — APPROVED** [review]
i have tested this. and it worked properly

**Comment by mohebifar** [comment]
Thanks! I'll merge and release this later today.

**Comment by mohebifar** [comment]
Released in `3.3.2`

**Pull request merged**
