### PR TITLE
I18n labels

### PR DESCRIPTION
**Pull request by milansusnjar**
Add option to localize step labels Skip, Previous, Next, Finish.

### CODE REVIEW

**Comment by milansusnjar** [comment]
@mohebifar I'd like to ping you politely about this.
Thanks.

**Comment by mohebifar** [comment]
Hey @milansusnjar. I'm so sorry for the delay. Can you please rebase against master? These changes look good to me. I just want to see Travis build before merging it.

PS. Since we moved repo away from OKGrow's SemaphoreCI account, I had to setup CI again.

**Comment by milansusnjar** [comment]
@mohebifar It should be up to date now. Thanks.

**Comment by jguix** [comment]
Ping

**Pull request merged**
