### PR TITLE
feat(tooltip): add getNth function

### PR DESCRIPTION
**Pull request by jakequade**
Straightforward function that allows a tooltip to send users to a specific step.

Tests added and all ✅ locally.

Original reason for implementing is it's a simple way to "pick up the tutorial" at any given point. Let's say the user has a few different tour steps, but they're activated by way of user action (or any external action). This function allows those external inputs to access a tour step directly.

### CODE REVIEW

**Comment by jakequade** [comment]
@mohebifar was hoping you might have a few minutes to this. Thanks mate!

**Comment by mohebifar** [comment]
Thanks! Could you please add some description to the readme as well?

**Comment by jakequade** [comment]
Sure thing - have added a brief explainer given there wasn't any prior one for tooltip components.

**Comment by jakequade** [comment]
Have updated the docs to be a little more explicit on how navigation works in general - keen on thoughts @mohebifar when you get a chance :) thanks so much!

**Comment by jakequade** [comment]
@mohebifar was hoping to get this merged if it looks okay, would save me having to use a fork. It also seems like it would be v useful.

Anyways, thanks for your time, I'll jump on any suggested changes.

**Comment by mohebifar** [comment]
Thank you! It should be available in 2.6.0

**Comment by jakequade** [comment]
Thanks so much mate! Really appreciated. If you're open to issues PRs, I might take a look at a few of the open ones. No problem if you'd prefer to leave it here. Have a good rest of the week!

**Comment by mohebifar** [comment]
It'd be much appreciated! 🙏

**Pull request merged**
