### PR TITLE
Scrollview support and typings

### PR DESCRIPTION
**Pull request by jguix**
Added scrollview support together with README instructions.

Added typings for typescript support.

### CODE REVIEW

**Comment by jguix** [comment]
Please note I am building on top of the work of @dancalifornia, and I updated some imports that were not working anymore.

**Comment by algarpe** [comment]
I was looking for this feature. It'd great to have it on master

**Comment by sanders-vag** [comment]
Thanks @jguix! This was something we need in our team, you made our day!

**Comment by henrymoulton** [comment]
Will this PR be merged in Travis goes green?

**Comment by simonasdev** [comment]
@mohebifar any chance of merging this any time soon?

@jguix maybe you could rebase your branch from master so it could be used in the meantime?

**Comment by mohebifar** [comment]
@jguix Thanks for this. This is great! Merging it to a transient branch for now and will release it after rebase.

**Comment by mohebifar** [comment]
It's been published in v2.4.7

**Comment by ducpt2** [comment]
@mohebifar thank you for great lib. 
I have a question, i using v2.4.7 with TypeScript and it still error, can you explain it? or i'm missing something?

**Pull request merged**
