### PR TITLE
Initial scrollview support

### PR DESCRIPTION
**Pull request by dancalifornia**
Added optional scrollview support. 

If a scrollview ref is provided, I set a slight timeout before measuring the next step.  There is no callback / event that I am aware of on scrollTo finish for me to call moveToCurrentStep.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Thanks, @dancalifornia. @mohebifar, can you take a look at this at some point? :)

**Comment by RichardLitt** [comment]
@mohebifar Ping. :)

**Comment by mohebifar** [comment]
Hi @dancalifornia, thanks for the PR!

Can you please share a snack example and add a short instruction to the README on how to use this feature?

**Comment by AE0011** [comment]
any solution?

**Pull request closed without merging**
