### PR TITLE
Custom mask path

### PR DESCRIPTION
**Pull request by czystyl**
I added an option to pass the custom path function for `SVG`.

The PR also can resolve one of issue #114 where someone wants to change the mask area.

### CODE REVIEW

**Comment by mohebifar** [comment]
Thank for the PR. Sorry for the delayed response. I'll review this later today.

**Comment by mohebifar** [comment]
@czystyl Could you please rebase against master?

**Comment by czystyl** [comment]
@mohebifar Done 👍

**Comment by pjay79** [comment]
Nice work

**Comment by andho** [comment]
I was looking for this exactly and found this through issue #114. When can this be merged?

**Comment by mohebifar** [comment]
This PR breaks the default rectangular SVG mask. The SVG function now expects named arguments instead of separate args and therefore the default function must be updated as well.

```diff
- const defaultSvgPath = (size, position, canvasSize): string => `M0,0H${canvasSize.x}V${canvasSize.y}H0V0ZM${position.x._value},${position.y._value}H${position.x._value + size.x._value}V${position.y._value + size.y._value}H${position.x._value}V${position.y._value}Z`
+ const defaultSvgPath = ({ size, position, canvasSize }): string => `M0,0H${canvasSize.x}V${canvasSize.y}H0V0ZM${position.x._value},${position.y._value}H${position.x._value + size.x._value}V${position.y._value + size.y._value}H${position.x._value}V${position.y._value}Z`
```

Other than that, it LGTM. I'll merge this into another branch and continue working on it and will merge it.

**Pull request merged**
